export const coursesInfo = [
    {
      id: 1,
      title: "Power BI",
      description: "This is an in-depth course on Power BI...",
      duration: "10 weeks",
      startDate: "2024-10-01",
      imageUrl: "https://codewave.com/insights/wp-content/uploads/2022/08/mern-stack-header-codewave.jpg",
      trending: "New",
      stars: "★★★★★",
      skillLevel: "Intermediate",
      topicsCovered: ["Data Analysis", "Visualization", "Reporting"],
      prerequisites: ["Basic Excel Skills", "Understanding of Data"],
      aboutCourse: "This course covers how to use Power BI for data analysis...",
      syllabus: [
        "Introduction to Power BI",
        "Connecting Data Sources",
        "Building Dashboards",
        "Advanced Reporting",
      ],
      keyFeatures: [
        "Comprehensive training",
        "Real-world projects",
        "Expert instructors",
      ],
      feesStructure: "$499",
      introduction: "In this course, you will learn how to create interactive reports and dashboards using Power BI.",
      instructor: "John Doe",
    },
    {
      id: 2,
      title: "AI Developer",
      description: "Learn about AI development...",
      duration: "8 weeks",
      startDate: "2024-11-01",
      imageUrl: "https://s3.us-east-1.amazonaws.com/asugv5-assets/archive/uploads/images/main/_featureLarge/artificial-intelligence.jpg",
      trending: "Trending",
      stars: "★★★★☆",
      skillLevel: "Advanced",
      topicsCovered: ["Machine Learning", "Deep Learning", "AI Ethics"],
      prerequisites: ["Python Programming", "Linear Algebra"],
      aboutCourse: "This course dives deep into AI development using the latest tools...",
      syllabus: [
        "AI Fundamentals",
        "Neural Networks",
        "AI in Business",
      ],
      keyFeatures: [
        "Latest AI tools and techniques",
        "Industry-specific case studies",
        "Hands-on projects",
      ],
      feesStructure: "$599",
      introduction: "This course focuses on building AI models and understanding the ethical considerations around AI development.",
      instructor: "Jane Smith",
    },
    // Add more courses as needed...
  ];
  