
const courses = [

  {
    title: "Power BI" ,
    description: "data modeling, visualization, and reporting to transform raw data into actionable insights",
    duration: "3 Months",
    date: "2024-10-01",
    imageUrl: "https://codewave.com/insights/wp-content/uploads/2022/08/mern-stack-header-codewave.jpg", // Example image URL
    trending: "Trending",
    stars: "★★★★★", // Example star rating
    skillTitle1: "Data Modeling and Analysis ",
    skillTitle2: "Data Visualization ",
    skillTitle3: "DAX (Data Analysis Expressions) for advanced calculations ",
    instructor: "Ajay Sit",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1:"Build and optimize data models for reporting.",
    learningPoint2:"Create compelling visuals and dashboards with Power BI.",
    learningPoint3:"Use DAX to perform complex data calculations.",
    syllabus1:"Introduction to Power BI and its architecture.",
    syllabus2:"Data connections, transformations, and modeling.",
    syllabus3:"Creating visual reports and dashboards.",
    syllabus4:"Using DAX for advanced analytics.",
    keyfeatures1:"Hands-on project-based learning.",
    keyfeatures2:"Industry-relevant case studies.",
    keyfeatures3:"Certification upon course completion.",
  },
  {
    title: "AR Caller/RCM",
    description: "managing healthcare claims, billing processes, and handling accounts.",
    duration: "8 weeks",
    date: "2024-11-01",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSIWhDDeO5Z2WjH5pz7t4iYjqQjznG-CW_-w&s",
    trending: "Trending",
    stars: "★★★★☆",
    skillTitle1: "Medical Billing and Coding ",
    skillTitle2: "Claims Management",
    skillTitle3: "Accounts Receivable Follow-up",    
    instructor: "John Doe",
    contact: "9545450788 / 9545450677",
    fees: "15,000",
    learningPoint1: "Handling insurance claims and denials",
    learningPoint2: "Managing accounts receivables and collections",
    learningPoint3: "Understanding the revenue cycle in healthcare",
    syllabus1:"Introduction to RCM: Overview of the healthcare revenue cycle and key stakeholders.",
    syllabus2:"Claims Processing: Submitting claims, resolving denials, and appeals.",
    syllabus3:"AR Follow-up: Techniques for managing unpaid claims and collections.",
    syllabus4:"Working with Claim Adjustments.",
    keyfeatures1:"Real-time case studies for better understanding",
    keyfeatures2:"Hands-on practice with billing software",
    keyfeatures3:"Industry-standard tools and techniques for AR follow-up",
  },
  {
    title: "SAP",
    description: "focusing on integrating various business processes such as finance, sales, logistics, and human resources.",
    duration: "30 Days",
    date: "2024-11-01",
    imageUrl: "https://img.freepik.com/free-vector/virtual-reality-glasses-technology_18591-52125.jpg?ga=GA1.1.945694213.1713233522&semt=ais_hybrid", // Example image URL
    trending: "Trending",
    stars: "★★★★☆",
    skillTitle1: "SAP Financial Accounting (FI)",
    skillTitle2: "SAP Materials Management (MM)",
    skillTitle3: "SAP Sales and Distribution (SD)", 
    instructor: "Satish Sir",
    contact: "9545450788 / 9545450677",
    fees: "15000",
    learningPoint1:"Managing financial transactions using SAP FI",
    learningPoint2:"Handling procurement and inventory processes in SAP MM",
    learningPoint3:"Implementing sales and order management with SAP SD",
    syllabus1:"Introduction to SAP ERP: Overview of modules and navigation.",
    syllabus2:"Financial Accounting (FI): General ledger, accounts payable/receivable, and asset accounting.",
    syllabus3:"Materials Management (MM) ",
    syllabus4:"Procurement, inventory management, and material valuation.",
    keyfeatures1:"Hands-on experience with SAP modules and real-time scenarios",
    keyfeatures2:"Case studies on enterprise resource planning.",
    keyfeatures3:"In-depth training in finance, logistics, and sales modules",
  },
  
  {
    title: " Medical Coding/Billing ",
    description: "transfor healthcare services into standardized codes and managing billing procedures.",
    duration: "3 Months",
    date: "2024-12-01",
    imageUrl: "https://nividous.com/wp-content/uploads/2022/07/artificial-intelligence-in-medical-billing-an-introduction-nividous.jpg", // Example image URL
    trending: "Trending",
    stars: "★★★★☆", // Example star rating
    skillTitle1: "ICD-10 and CPT Coding ",
    skillTitle2: "Medical Billing Procedures",
    skillTitle3: "Healthcare Compliance and Regulations", 
    instructor: "Manisha Mam",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1:"Understanding medical terminologies and coding standards",
    learningPoint2:"Processing insurance claims and billing",
    learningPoint3:"Ensuring compliance with healthcare regulations",
    syllabus1:"Introduction to Medical Coding: ICD-10, CPT, and HCPCS coding systems",
    syllabus2:"Billing Procedures: Insurance claims, reimbursement processes, and payment follow-up.",
    syllabus3:"Compliance and Regulations",
    syllabus4:": HIPAA guidelines and healthcare compliance.",
    keyfeatures1:"Hands-on training in coding and billing software",
    keyfeatures2:"Real-world case studies to enhance practical knowledge",
    keyfeatures3:"Comprehensive understanding of healthcare insurance policies and claim processes",
  },

  {
    title: "AWS Administrator",
    description: "managing and operating AWS cloud infrastructure, focusing on deploying, managing, and troubleshooting AWS services.",
    duration: "6 months",
    date: "2024-12-01",
    imageUrl: "https://www.spoclearn.com/blog/wp-content/uploads/2023/12/AI-and-Power-BI-A-Powerful-Combination-for-Data-Visualization.jpg", // Example image URL
    trending: "Trending",
    stars: "★★★★☆", // Example star rating
    skillTitle1: "Cloud Infrastructure Management ",
    skillTitle2: "AWS Security and Compliance",
    skillTitle3: "Cost Optimization Strategies", 
    instructor: "Lekharaj Sir",
    contact: "9545450788 / 9545450677",
    fees: "35000",
    learningPoint1:"Setting up and managing AWS environments",
    learningPoint2:"Securing AWS resources and managing user permissions",
    learningPoint3:"Optimizing cloud resources and reducing costs",
    syllabus1:"AWS Overview: Introduction to AWS services and architecture.",
    syllabus2:"EC2 and Storage Services: Managing EC2 instances, S3 storage, and EBS volumes.",
    syllabus3:"VPC & Networking: Configuring virtual private clouds, subnets, and routing.",
    syllabus4:"Monitoring & Troubleshooting: Using CloudWatch, CloudTrail, and troubleshooting AWS issues.",
    keyfeatures1:"Hands-on experience with AWS management tools",
    keyfeatures2:"Real-world projects for cloud infrastructure setup",
    keyfeatures3:"AWS best practices for security and cost optimization",
  },
  {
    title: "Soft Skills",
    description: "improve  interpersonal and communication skills, enhancing teamwork, leadership, and problem-solving capabilities",
    duration: "12 weeks",
    date: "2024-12-01",
    imageUrl: "https://img.freepik.com/free-vector/soft-skills-concept-illustration_114360-8984.jpg?ga=GA1.1.945694213.1713233522&semt=ais_hybrid", // Example image URL
    trending: "New",
    stars: "★★★★★", // Example star rating
    skillTitle1: "Communication & Presentation",
    skillTitle2: "Teamwork & Collaboration",
    skillTitle3: "Problem-solving & Critical Thinking", 
    instructor: "Hello",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1:"Effective communication techniques in professional settings",
    learningPoint2:"Building strong teamwork and leadership skills",
    learningPoint3:"Enhancing emotional intelligence and adaptability",
    syllabus1:"Communication Skills: Verbal, non-verbal, and written communication strategies.",
    syllabus2:"Leadership & Teamwork: Leading teams, conflict resolution, and collaboration.",
    syllabus3:"Time Management & Productivity: Prioritization, setting goals, and managing tasks.",
    syllabus4:"Emotional Intelligence: Understanding and managing emotions in workplace scenarios.",
    keyfeatures1:"Interactive role-playing and case studies for real-world scenarios",
    keyfeatures2:"Personalized feedback on presentations and teamwork",
    keyfeatures3:"Practical exercises to improve leadership and emotional intelligence",
  },
  {
    title: "Software Testing",
    description: "software testing methodologies, tools, and best practices to ensure the delivery of high-quality software products.",
    duration: "12 weeks",
    date: "2024-12-01",
    imageUrl: "https://pixelplex.io/wp-content/uploads/2021/01/artificial-intelligence-applications-in-healthcare-main-image-1600.jpg", // Example image URL
    trending: "New",
    stars: "★★★★★", // Example star rating
    skillTitle1: "Test Planning & Design",
    skillTitle2: "Automation Testing",
    skillTitle3: "Defect Tracking & Management", 
    instructor: "Hello",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1:"Key concepts and types of software testing (manual and automated)",
    learningPoint2:"Effective test planning, design, and execution",
    learningPoint3:"Use of testing tools for automation and defect tracking",
    syllabus1:"Introduction to Software Testing: Overview of testing principles, life cycle, and types of testing (functional, non-functional, etc.).",
    syllabus2:"Test Planning & Design: Test strategy, test case design techniques, and test documentation.",
    syllabus3:"Automation Testing: Introduction to automation frameworks and tools (e.g., Selenium, QTP).",
    syllabus4:"Defect Tracking & Management: Defect life cycle, tools for tracking defects (e.g., JIRA), and reporting.",
    keyfeatures1:"Hands-on projects to apply testing concepts in real-world scenarios",
    keyfeatures2:"Access to industry-standard testing tools and software",
    keyfeatures3:"Comprehensive assessments to evaluate learning progress and understanding",
   
  },
  {
    title: "Sales Force Adm/Dev",
    description: " manage and customize Salesforce applications, focusing on both administrative tasks and development capabilities.",
    duration: "12 weeks",
    date: "2024-12-01",
    imageUrl: "https://s3.us-east-1.amazonaws.com/asugv5-assets/archive/uploads/images/main/_featureLarge/artificial-intelligence.jpg", // Example image URL
    trending: "New",
    stars: "★★★★★", // Example star rating
    skillTitle1: "Salesforce Administration",
    skillTitle2:"Apex Programming",
    skillTitle3:"Data Management & Security", 
    instructor: "Hello",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1:"Configuration and customization of Salesforce platforms to meet business needs",
    learningPoint2:"Development of applications using Apex and Visualforce",
    learningPoint3:"Best practices for data management and security within Salesforce",
    syllabus1:"Salesforce Administration: User setup, role management, profiles, and permission sets.",
    syllabus2:"Customization & Configuration: Custom objects, fields, validation rules, and workflows.",
    syllabus3:"Apex Programming: Introduction to Apex, triggers, and classes; building custom business logic.",
    syllabus4:"Data Management: Data import/export, data quality, security settings, and sharing rules.",
    keyfeatures1:"Hands-on labs for practical experience with Salesforce tools and features",
    keyfeatures2:"Real-world case studies to understand best practices and solutions",
    keyfeatures3:"Certification preparation to help you pass Salesforce Admin and Developer exams",
  },
  {
    title: "Data Science",
    description: "This course provides a comprehensive introduction to data science, covering essential tools and techniques for data analysis, visualization, and machine learning..",
    duration: "12 weeks",
    date: "2024-12-01",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtn5OeXYY8PsnhU537FI_pEC4BVbI3McDdPg&s",
    trending: "New",
    stars: "★★★★☆", // Example star rating
    skillTitle1: "Statistical Analysis",
    skillTitle2: " Data Visualization",
    skillTitle3: "Machine Learning Algorithms", 
    instructor: "Hello",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1:"Data manipulation and analysis using Python and R.",
    learningPoint2:"Techniques for visualizing data to derive insights.",
    learningPoint3:"Implementation of machine learning algorithms for predictive modeling.",
    syllabus1:"Introduction to Data Science: Overview of data science, data types, and data lifecycle.",
    syllabus2:"Data Analysis: Using libraries like Pandas and NumPy for data manipulation and analysis.",
    syllabus3:"Data Visualization: Creating visualizations using Matplotlib and Seaborn.",
    syllabus4:"Machine Learning: Supervised and unsupervised learning techniques, model evaluation, and deployment.",
    keyfeatures1:"Hands-on projects to apply data science concepts in real-world scenarios.",
    keyfeatures2:"Access to datasets for practical experience in data analysis and machine learning.",
    keyfeatures3:"Guidance on building a portfolio to showcase data science skills to potential employers.",
  },
  {
    title: "Machine Learning ",
    description: "This course delves into the principles and applications of machine learning, equipping learners with the skills to develop and implement machine learning algorithms for various tasks.",
    duration: "12 weeks",
    date: "2024-12-01",
    imageUrl: "https://miro.medium.com/v2/resize:fit:1400/1*cG6U1qstYDijh9bPL42e-Q.jpeg", // Use the imported Img variable
    trending: "New",
    stars: "★★★★★", // Example star rating
    skillTitle1: " Algorithm Selection",
    skillTitle2: "Model Training and Evaluation ",
    skillTitle3: " Data Preprocessing Techniques", 
    instructor: "Hello",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1:"Fundamentals of supervised and unsupervised learning.",
    learningPoint2:"Techniques for feature selection and data preprocessing.",
    learningPoint3:"Implementation of common algorithms such as regression, classification, and clustering.",
    syllabus1:"Introduction to Machine Learning: Overview of machine learning concepts, types, and applications.",
    syllabus2:"Data Preparation: Data cleaning, normalization, and feature engineering.",
    syllabus3:"Supervised Learning Algorithms: Linear regression, decision trees, support vector machines (SVM).",
    syllabus4:"Unsupervised Learning Algorithms: K-means clustering, hierarchical clustering, and principal component analysis (PCA).",
    keyfeatures1:"Practical assignments to reinforce learning through hands-on experience.",
    keyfeatures2:"Real-world case studies to understand the application of machine learning in various industries.",
    keyfeatures3:"Access to popular machine learning libraries like scikit-learn and TensorFlow for building models.",
  },
  {
    title: "Python",
    description: "This course provides a comprehensive introduction to Python programming, covering essential concepts and practical applications for both beginners and experienced programmers.",
    duration: "12 weeks",
    date: "2024-12-01",
    imageUrl: "https://www.damcogroup.com/wp-content/uploads/2023/12/python-for-ai-and-ml.jpg", // Use the imported Img variable
    trending: "New",
    stars: "★★★★☆", // Example star rating
    skillTitle1: "Basic Syntax and Data Types",
    skillTitle2: " Control Structures and Functions",
    skillTitle3: " Object-Oriented Programming", 
    instructor: "Hello",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1:"Fundamental programming concepts, including variables, loops, and conditionals.",
    learningPoint2:"How to write reusable functions and handle exceptions effectively.",
    learningPoint3:"Basics of object-oriented programming, including classes and inheritance",
    syllabus1:"Introduction to Python: Overview of Python, installation, and setting up the environment.",
    syllabus2:"Data Structures: Lists, tuples, dictionaries, and sets.",
    syllabus3:"Control Flow: Conditional statements, loops, and iteration techniques.",
    syllabus4:"Modules and Libraries: Understanding Python modules, packages, and popular libraries like NumPy and Pandas.",
    keyfeatures1:"Hands-on projects to apply Python skills in real-world scenarios.",
    keyfeatures2:"Comprehensive quizzes and assignments to reinforce learning.",
    keyfeatures3:"Access to a community forum for collaboration and support.",
  },
  {
    title: "Java And ASP.Net",
    description: "This course offers a thorough introduction to Java programming, focusing on object-oriented concepts and application development for building robust software solutions.",
    duration: "12 weeks",
    date: "2024-12-01",
    imageUrl: "https://www.damcogroup.com/wp-content/uploads/2023/12/python-for-ai-and-ml.jpg", // Use the imported Img variable
    trending: "New",
    stars: "★★★★☆", // Example star rating
    skillTitle1: " Object-Oriented Programming (OOP)",
    skillTitle2: " Java Collections Framework",
    skillTitle3: " Exception Handling and Multithreading", 
    instructor: "Hello",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1:"Core Java concepts, including classes, objects, inheritance, and polymorphism.",
    learningPoint2:"Utilizing the Java Collections Framework for efficient data management.",
    learningPoint3:"Implementing error handling and multithreading for concurrent applications.",
    syllabus1:"Java Basics: Introduction to Java, setup, syntax, and data types.",
    syllabus2:"OOP Concepts: Classes, objects, inheritance, and encapsulation.",
    syllabus3:"Collections and Generics: Understanding collections, maps, and using generics.",
    syllabus4:"Exception Handling and Threads: Error handling, creating threads, and synchronization.",
    keyfeatures1:"Hands-on coding exercises and projects to build real-world applications.",
    keyfeatures2:"Comprehensive assessments and quizzes to track progress.",
    keyfeatures3:"Access to resources and community support for problem-solving.  ",
  },
  {
    title: "Business Analyst",
    description: "This course equips learners with essential skills to analyze business needs, facilitate communication between stakeholders, and drive successful project outcomes through effective data analysis.",
    duration: "12 weeks",
    date: "2024-12-01",
    imageUrl: "https://www.damcogroup.com/wp-content/uploads/2023/12/python-for-ai-and-ml.jpg", // Use the imported Img variable
    trending: "New",
    stars: "★★★★★", // Example star rating
    skillTitle1: " Requirements Gathering and Documentation",
    skillTitle2: " Data Analysis and Visualization",
    skillTitle3: " Stakeholder Communication and Management", 
    instructor: "Hello",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1:"Techniques for eliciting and documenting business requirements from stakeholders.",
    learningPoint2:"Utilizing data analysis tools to interpret and visualize data for informed decision-making.",
    learningPoint3:"Strategies for effective communication and collaboration with project teams and stakeholders.",
    syllabus1:"Introduction to Business Analysis: Role of a business analyst, key concepts, and methodologies.",
    syllabus2:"Requirements Engineering: Techniques for gathering, documenting, and validating requirements.",
    syllabus3:"Data Analysis Techniques: Exploring data analysis methods, tools, and visualization techniques.",
    syllabus4:"Stakeholder Engagement: Building relationships, managing expectations, and facilitating communication.",
    keyfeatures1:"Case studies and real-world scenarios to apply business analysis concepts.",
    keyfeatures2:"Hands-on exercises using popular data analysis tools and software.",
    keyfeatures3:"Networking opportunities with industry professionals and peers for knowledge sharing.",
  },
  {
    title: "Digital Marketing",
    description: "This course provides a comprehensive overview of digital marketing strategies, tools, and techniques to effectively promote products and services online, driving engagement and conversions.",
    duration: "12 weeks",
    date: "2024-12-01",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4VpF4XXNnpvJSB_KPV6dOVQx2Mmd_kPY3Kg&s", // Example image URL
    trending: "New",
    stars: "★★★★☆", // Example star rating
    skillTitle1: " Search Engine Optimization (SEO)",
    skillTitle2: " Social Media Marketing",
    skillTitle3: " Content Marketing and Email Campaigns", 
    instructor: "Hello",
    contact: "9545450788 / 9545450677 " ,
    fees: "30000",
    learningPoint1:"Strategies for optimizing websites to rank higher in search engine results.",
    learningPoint2:"Techniques for creating and managing effective social media marketing campaigns.",
    learningPoint3:"Best practices for developing content that attracts and retains customers.",
    syllabus1:"Introduction to Digital Marketing: Overview of digital marketing channels and trends.",
    syllabus2:"Search Engine Optimization (SEO): On-page and off-page SEO techniques and tools.",
    syllabus3:"Social Media Strategies: Building a social media presence and managing platforms like Facebook, Instagram, and LinkedIn.",
    syllabus4:"Email Marketing Campaigns: Creating, executing, and analyzing email marketing strategies.",
    keyfeatures1:"Hands-on projects to implement digital marketing strategies in real-world scenarios.",
    keyfeatures2:"Case studies from successful digital marketing campaigns.",
    keyfeatures3:"Insights from industry experts and guest speakers on current trends and best practices.",
  },

  {
    title: "Dev-Ops",
    description: "focusing on collaboration between development and operations teams to improve efficiency, reduce time to market, and ensure high-quality software delivery.",
    duration: "12 weeks",
    date: "2024-12-01",
    imageUrl: "https://sourcebae.com/blog/wp-content/uploads/2023/08/top-ai-programming-languages.png",
    trending: "Trending",
    stars: "★★★☆☆",
    skillTitle1: "Continuous Integration/Continuous Deployment (CI/CD)",
    skillTitle2: " Infrastructure as Code (IaC)",
    skillTitle3: " Monitoring and Logging", 
    instructor: "Hello",
    contact: "9545450788 / 9545450677",
    fees: "30000",
    learningPoint1: "Key DevOps concepts and methodologies to enhance collaboration across teams.",
    learningPoint2: "Tools and techniques for automating the software delivery process.",
    learningPoint3: "Strategies for monitoring applications and infrastructure to ensure performance and reliability.",
    syllabus1:"Introduction to DevOps: Understanding the DevOps culture, principles, and practices.",
    syllabus2:"Continuous Integration and Continuous Deployment (CI/CD): Implementing CI/CD pipelines with tools like Jenkins, GitLab, and CircleCI.",
    syllabus3:"Infrastructure as Code (IaC): Utilizing tools like Terraform and Ansible for automating infrastructure management.",
    syllabus4:"Monitoring and Logging: Setting up monitoring systems using Prometheus, Grafana, and ELK Stack to track application performance.",
    keyfeatures1:"Hands-on labs to practice real-world DevOps tools and techniques.",
    keyfeatures2:"Collaborative projects to foster teamwork between development and operations.",
    keyfeatures3:"Insights from industry professionals on DevOps best practices and emerging trends.",
  },
];
export default courses;